# Generated by Django 4.1.7 on 2023-12-06 14:21

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Restaurant",
            fields=[
                (
                    "restaurantName",
                    models.CharField(max_length=255, primary_key=True, serialize=False),
                ),
                ("style", models.CharField(max_length=255)),
                ("price", models.CharField(max_length=255)),
                ("address", models.CharField(max_length=255)),
                ("zip", models.CharField(max_length=255)),
            ],
            options={
                "db_table": "Restaurants",
            },
        ),
        migrations.CreateModel(
            name="Users",
            fields=[
                ("userID", models.AutoField(primary_key=True, serialize=False)),
                ("userName", models.CharField(max_length=255)),
                ("password", models.CharField(max_length=255)),
            ],
            options={
                "db_table": "Users",
            },
        ),
        migrations.CreateModel(
            name="Rating",
            fields=[
                ("ratingID", models.AutoField(primary_key=True, serialize=False)),
                ("score", models.IntegerField()),
                ("comment", models.TextField()),
                (
                    "restaurantName",
                    models.ForeignKey(
                        db_column="restaurantName",
                        on_delete=django.db.models.deletion.CASCADE,
                        to="restaurant_search.restaurant",
                    ),
                ),
            ],
            options={
                "db_table": "Rating",
            },
        ),
        migrations.CreateModel(
            name="History",
            fields=[
                ("historyID", models.AutoField(primary_key=True, serialize=False)),
                ("input", models.CharField(max_length=255)),
                (
                    "userID",
                    models.ForeignKey(
                        db_column="userID",
                        on_delete=django.db.models.deletion.CASCADE,
                        to="restaurant_search.users",
                    ),
                ),
            ],
            options={
                "db_table": "History",
            },
        ),
        migrations.CreateModel(
            name="Favorites",
            fields=[
                ("favoriteID", models.AutoField(primary_key=True, serialize=False)),
                ("restaurantName", models.CharField(max_length=255)),
                ("note", models.CharField(max_length=255)),
                (
                    "userID",
                    models.ForeignKey(
                        db_column="userID",
                        on_delete=django.db.models.deletion.CASCADE,
                        to="restaurant_search.users",
                    ),
                ),
            ],
            options={
                "db_table": "Favorites",
            },
        ),
    ]
